version: "3.0"
# i want to add username and password for sql server
services:
  sqlserverdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserverdb
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - SA_PASSWORD=Truong123@
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
      - ./database/init-database/backup/:/backups
    networks:
      - sqlnet

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - DB_SERVER=sqlserverdb
      - DB_USER=sa
      - DB_PASSWORD=Truong123@
      - DB_NAME=PETCAREX
    depends_on:
      - sqlserverdb
    networks:
      - sqlnet

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "4173:4173"
    depends_on:
      - backend
    networks:
      - sqlnet

volumes:
  sqlserverdata:
networks:
  sqlnet:
    driver: bridge
